apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatekeeper.fullname" . }}
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- tpl (.Values.config | toYaml) $ | nindent 4 }}
